import { useEffect, useRef, useState } from 'react';
import { audioEngine, saveLocal, type Playback } from '../audio/AudioEngine';
import { tracks } from '../audio/tracks';
import { PixelCharacter } from '../character/PixelCharacter';
import { menuItems, type PlayerUI } from '../hooks/usePlayerUI';
import { pets } from '../character/characterFrames';
import { PetThumbnail } from '../character/PetThumbnail';
import { PixelIcon } from './PixelIcon';
const time=(value:number)=>`${Math.floor(value/60)}:${String(Math.floor(value%60)).padStart(2,'0')}`;
function Marquee({text}:{text:string}){const container=useRef<HTMLDivElement>(null),content=useRef<HTMLSpanElement>(null);const [overflow,setOverflow]=useState(0);useEffect(()=>{const measure=()=>setOverflow(Math.max(0,(content.current?.scrollWidth||0)-(container.current?.clientWidth||0)));measure();void document.fonts.ready.then(measure)},[text]);return <div className={`marquee ${overflow?'scrolling':''}`} ref={container} style={{'--travel':`-${overflow+12}px`} as React.CSSProperties}><span ref={content}>{text}</span></div>}
function Progress({state}:{state:Playback}){return <input className="pixel-progress" type="range" aria-label="Track progress" min={0} max={1000} value={state.duration?Math.round(state.currentTime/state.duration*1000):0} onChange={e=>audioEngine.seek(Number(e.target.value)/1000)} style={{'--progress':`${state.duration?state.currentTime/state.duration*100:0}%`} as React.CSSProperties}/>}
export function LCDScreen({state,ui}:{state:Playback;ui:PlayerUI}){
 const [clock,setClock]=useState(()=>new Date());useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),30000);return()=>clearInterval(timer)},[]);
 const track=tracks[state.currentTrackIndex];const favorited=track&&ui.favorites.includes(track.id);
 const listRef=useRef<HTMLDivElement>(null);useEffect(()=>{listRef.current?.querySelector('[aria-current="true"]')?.scrollIntoView({block:'nearest'})},[ui.selection,ui.screen]);
 const list=(items:{label:string;detail?:string;action:()=>void}[])=><div className="lcd-list" ref={listRef}>{items.map((item,i)=><button key={i} aria-current={ui.selection===i} className={ui.selection===i?'selected':''} onPointerEnter={()=>ui.setSelection(i)} onClick={item.action}><span className="row-arrow">▸</span><span className="row-title">{item.label}</span>{item.detail&&<span className="row-detail">{item.detail}</span>}</button>)}</div>;
 const heading=(text:string,icon:string)=><div className="screen-heading"><PixelIcon name={icon} size={19}/><span>{text}</span></div>;
 const pet=<PixelCharacter pet={ui.selectedPet} playing={state.isPlaying} sleeping={ui.sleeping} hasPlayed={state.hasPlayed} mode={ui.mode}/>;
 let body;
 if(ui.booting)body=<div className="boot-copy"><span className="boot-logo">TAMA</span><br/>HELLO, FRIEND.<div className="boot-dots">▪ ▪ ▪</div></div>;
 else switch(ui.screen){
 case 'home':body=<>{pet}{state.error?<div className="track-error"><strong>{state.error}</strong><span>{tracks.length?'TRY NEXT →':'ADD MUSIC TO tracks/'}</span></div>:<><button className="track-name text-button" onClick={()=>ui.open('details')} aria-label="Open track details"><Marquee text={ui.sleeping?'Good night':state.loading?'Feeding track...':track?.title||'Your music goes here'}/></button><div className="artist">{ui.sleeping?'z z z':state.loading?'just a moment':track?.artist}</div><Progress state={state}/></>}</>;break;
 case 'menu':body=<>{heading('MENU','music')}<div className="menu-grid">{menuItems.map((item,i)=><button key={item.screen} aria-label={item.label} aria-current={ui.selection===i} className={ui.selection===i?'selected':''} onPointerEnter={()=>ui.setSelection(i)} onClick={()=>ui.open(item.screen)}><PixelIcon name={item.icon} size={32}/><span>{item.label}</span></button>)}</div><div className="lcd-hint">SELECT · ENTER · BACK</div></>;break;
 case 'music':body=<>{heading('TRACKS','music')}{list(tracks.map((t,i)=>({label:t.title,detail:i===state.currentTrackIndex?'♪':undefined,action:()=>ui.choose(i)})))}{!tracks.length&&<div className="empty-state">No tracks yet.<br/>Add audio to tracks/.</div>}<div className="lcd-hint">{tracks.length} TRACKS / LOCAL COLLECTION</div></>;break;
 case 'favorites':body=<>{heading('FAVORITES','heart')}{list([{label:favorited?'Remove current':'Save current',detail:favorited?'♥':'+',action:ui.toggleFavorite},...ui.favoriteTracks.map((t,i)=>({label:t.title,action:()=>ui.choose(i+1)}))])}{!ui.favoriteTracks.length&&<p className="empty-state">Keep your little<br/>favorites here.</p>}</>;break;
 case 'pet':body=<>{heading('PETS','pet')}<div className="pet-picker-strip">{pets.map((candidate,i)=><button key={candidate.id} aria-label={`Preview ${candidate.label.toLowerCase()}`} aria-current={ui.selection===i} className={ui.selection===i?'selected':''} onClick={()=>ui.setSelection(i)}><PetThumbnail pet={candidate.id}/></button>)}</div><div className="pet-picker-preview"><PixelCharacter pet={pets[ui.selection]?.id||ui.selectedPet} playing={state.isPlaying} sleeping={false} hasPlayed={state.hasPlayed}/></div><div className="pet-picker-name">{pets[ui.selection]?.label}<span>{ui.selection+1} / {pets.length}</span></div><button className="pet-choose" onClick={()=>ui.choose()}>{pets[ui.selection]?.id===ui.selectedPet?'♥ YOUR COMPANION':'CHOOSE THIS PET'}</button></>;break;
 case 'visual':body=<>{heading('VISUAL','bars')}{list(['PET','BARS','WAVE'].map((name,i)=>({label:name,detail:ui.mode===name?'●':'',action:()=>ui.choose(i)})))}<div className="lcd-hint">CHANGE THE WAY YOUR PET DANCES</div></>;break;
 case 'settings':body=<>{heading('SETTINGS','settings')}{list([{label:'Volume',detail:`${Math.round(state.volume*100)}%`,action:()=>ui.open('volume')},{label:'Screen',detail:ui.contrast?'DARK':'LCD',action:()=>ui.open('contrast')},{label:'About',detail:'›',action:()=>ui.open('about')}])}<div className="lcd-hint">MAKE YOURSELF AT HOME</div></>;break;
 case 'volume':body=<>{heading('VOLUME','music')}<div className="setting-value">{Math.round(state.volume*100)}<small>%</small></div><input className="volume-range" aria-label="Volume" type="range" min="0" max="100" step="1" value={Math.round(state.volume*100)} onChange={e=>audioEngine.setVolume(Number(e.target.value)/100)}/><div className="setting-ends"><span>QUIET</span><span>LOUD</span></div><div className="lcd-hint">LEFT +10 · MIDDLE DONE</div></>;break;
 case 'contrast':body=<>{heading('SCREEN','settings')}<div className="contrast-options">{[false,true].map((value,i)=><button key={i} className={ui.contrast===value?'selected':''} onClick={()=>{ui.setContrast(value);saveLocal('tama-contrast',value)}}>{value?'DARK':'CLASSIC'}<div className="contrast-sample">Aa ▦</div></button>)}</div><div className="lcd-hint">LEFT CHANGE · MIDDLE DONE</div></>;break;
 case 'about':body=<>{heading('ABOUT','pet')}<div className="about-copy"><strong>TAMA PLAYER</strong><span>VERSION 0.1</span><p>A little music.<br/>A little company.</p><span>YOUR LITTLE MUSIC COMPANION.</span></div></>;break;
 case 'details':body=<>{heading('NOW PLAYING','music')}<div className="detail-title"><Marquee text={track?.title||'No track'}/><div className="artist">{track?.artist}</div></div><Progress state={state}/><div className="play-time">{time(state.currentTime)} / {time(state.duration)}</div><div className="detail-controls"><button aria-label={favorited?'Remove from favorites':'Add to favorites'} aria-pressed={!!favorited} onClick={ui.toggleFavorite}>{favorited?'♥':'♡'}</button><span>{state.isPlaying?'PLAYING':'PAUSED'}</span><button aria-label="Return home" onClick={()=>ui.open('home')}><PixelIcon name="back" size={22}/></button></div></>;break;
 }
 return <section className={`lcd ${ui.contrast?'high-contrast':''} ${ui.booting?'booting':''}`} aria-label="Tama player LCD"><div className="statusbar"><button className="text-button menu-shortcut" onClick={()=>ui.open('menu')} aria-label="Open menu"><PixelIcon name="music" size={21}/></button><span>{clock.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span><span className="battery" aria-label="Battery full (decorative)"/></div><div key={ui.screen+(ui.booting?'boot':'')} className={`screen-content screen-${ui.screen}`}>{body}</div><span className="sr-only" role="status">{state.error||`${state.isPlaying?'Playing':'Paused'}: ${track?.title||'No tracks'}`}</span></section>;
}
